// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proje_bitirme.Models;

#nullable disable

namespace projebitirme.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615123013_AddTahminiTuketimColumn")]
    partial class AddTahminiTuketimColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("proje_bitirme.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgirlikKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeygirGucu")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Litre100Km")
                        .HasColumnType("REAL");

                    b.Property<double>("MotorHacmi")
                        .HasColumnType("REAL");

                    b.Property<double>("Mpg")
                        .HasColumnType("REAL");

                    b.Property<string>("Sanziman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Yil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("proje_bitirme.Models.AracVerisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AracSinifi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Emisyon")
                        .HasColumnType("REAL");

                    b.Property<double>("Litre100Km")
                        .HasColumnType("REAL");

                    b.Property<double>("MotorHacmi")
                        .HasColumnType("REAL");

                    b.Property<string>("Sanziman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Silindir")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Yil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AracVerileri");
                });
#pragma warning restore 612, 618
        }
    }
}
